<?xml version="1.0" encoding="UTF-8"?>
<!--
    Search-box visibility, derived from what the edition's DITAVAL DOES (issue #178).

    Fills in the empty placeholder declared by this overlay's
    page-templates-fragments/search-flag.xml, which the publishing template
    binds to the `webhelp.fragment.after.header` extension point - one of the
    few that reaches EVERY generated page type, including the two that are NOT
    built from a topic: the tiles landing page (built from the ditamap) and the
    dedicated search-results page (generated by Oxygen).

    THE SIGNAL IS `args.filter`, AND THAT IS THE POINT. The student edition is,
    by definition, the pass that filters out the instructor content - so the
    scenario parameter that MAKES it the student edition is also what identifies
    it. No second parameter to set, and nothing extra to remember when the
    scenarios are rebuilt from scratch.

    A dedicated `webhelp.show.search` parameter was tried first and rejected for
    exactly that reason: an operator who rebuilt the student scenario and forgot
    to re-add it would get a student edition with a dead search box, and nothing
    would say so. Forgetting `args.filter`, by contrast, is impossible to miss -
    the student build comes out carrying the instructor's Analysis Sheets and
    vessel names.

    WE TEST WHAT THE DITAVAL DOES, NOT WHAT IT IS CALLED. Matching the filename
    `trainee.ditaval` was tried and FAILED in a real publish, because by the time
    these pages are generated the filename is no longer ours:

      - DITA-OT's own preprocess merges the supplied DITAVAL(s) and writes
        <temp>/ditaot.generated.ditaval (org.dita.dost.module.MergeDitavalModule);
      - Oxygen's scenario Filters tab, if used instead of an explicit
        args.filter, generates a DITAVAL under a name of its own choosing.

    Reading the file and asking whether it excludes audience="-trainee" is
    immune to all of that, and says exactly what we mean: this is the pass with
    the instructor content taken out. `-trainee` is the audience token
    generate_dita.py stamps and trainee.ditaval excludes; it is the pipeline's
    own constant, not an operator choice.

    Oxygen makes args.filter readable because `whr-create-props-file` serialises
    EVERY Ant property of the build (an <echoproperties> with no @prefix), and
    oxyf:getParameter reads that file - so DITA-OT's own parameters are visible
    here alongside the template's.

    THE MARKER IS ALWAYS EMITTED, carrying either `wh-search-hidden` or
    `wh-search-shown`. Only the first does anything (see hide-search.css). The
    second exists so the mechanism is VISIBLE IN THE OUTPUT: this template is
    only exercised by a real Oxygen publish, which needs a licence the project
    does not have, so "did the fragment arrive, and how did the test evaluate?"
    has to be answerable by grepping a published page. An always-absent marker
    cannot distinguish "never got here" from "decided no".

    Fragment content included via <whc:include_html> is re-processed in
    `copy_template` mode by Oxygen's own commonComponentsExpander.xsl (see
    `includeCustomHTMLContent`), which is what lets this template match inside a
    fragment file rather than a forked page layout.

    WHY NOT INFER FROM PAGE CONTENT. The first version of this overlay did:
    generate_dita.py stamps an instructor-only <p class="gf-persistent"> marker
    on every TOPIC, the trainee DITAVAL strips it, and the CSS hid the box
    wherever the marker was absent. That inference is only available on pages
    built from a topic. index.html and search.html carry no marker in EITHER
    edition, so the instructor lost the search box on the tiles landing page -
    precisely where a reader arrives and reaches for it.
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:whc="http://www.oxygenxml.com/webhelp/components"
    xmlns:oxyf="http://www.oxygenxml.com/functions"
    xmlns:aaac="http://deepbluec.co.uk/ns/aaac/functions"
    exclude-result-prefixes="#all" version="2.0">

    <!--
        The audience token generate_dita.py stamps on instructor-only content
        and trainee.ditaval excludes. Excluding it IS what makes a build the
        student edition.
    -->
    <xsl:variable name="trainee-audience" as="xs:string" select="'-trainee'"/>

    <!--
        Turn a DITAVAL path from args.filter into something doc() can open.
        Windows absolute paths ("Z:\dita\trainee.ditaval") are the normal case
        on the delivered target and are not URIs; iri-to-uri escapes the spaces
        a mapped-drive path may well contain.
    -->
    <xsl:function name="aaac:to-url" as="xs:string">
        <xsl:param name="path" as="xs:string"/>
        <xsl:variable name="p" as="xs:string" select="translate(normalize-space($path), '\', '/')"/>
        <xsl:sequence select="
            if (matches($p, '^[a-zA-Z]:/')) then iri-to-uri(concat('file:/', $p))
            else if (starts-with($p, '/')) then iri-to-uri(concat('file://', $p))
            else if (matches($p, '^[a-zA-Z][a-zA-Z0-9+.-]*:')) then $p
            else iri-to-uri($p)"/>
    </xsl:function>

    <!--
        True when this run is the student edition. args.filter may name several
        DITAVALs separated by the platform path separator, so test each.

        Note the safe direction of failure: an unreadable, absent or
        unrecognised DITAVAL leaves the search box VISIBLE. A student edition
        with a useless search box is a wart; an instructor edition without one
        is a defect.
    -->
    <xsl:variable name="is-student-edition" as="xs:boolean" select="
        some $ditaval in tokenize(oxyf:getParameter('args.filter'), ';')[normalize-space(.) != '']
            satisfies (
                doc-available(aaac:to-url($ditaval))
                and exists(
                    doc(aaac:to-url($ditaval))//*:prop
                        [@att = 'audience']
                        [@val = $trainee-audience]
                        [lower-case(@action) = 'exclude'])
            )"/>

    <xsl:template match="*:div[contains(@class, 'wh_search_visibility')]" mode="copy_template">
        <!--
            Hidden either way: this is a signal, not content. The class carries
            the answer, and resources/hide-search.css acts on it - so the actual
            rule stays in the stylesheet where it can be read and overridden
            like any other style.
        -->
        <div hidden="hidden"
            class="wh_search_visibility {if ($is-student-edition)
                                         then 'wh-search-hidden'
                                         else 'wh-search-shown'}"/>
    </xsl:template>

</xsl:stylesheet>
