<?xml version="1.0" encoding="UTF-8"?>
<!--
    Search-box visibility, derived from the edition's DITAVAL (issue #178).

    Fills in the empty placeholder declared by this overlay's
    page-templates-fragments/search-flag.xml, which the publishing template
    binds to the `webhelp.fragment.after.header` extension point - one of the
    few that reaches EVERY generated page type, including the two that are NOT
    built from a topic: the tiles landing page (built from the ditamap) and the
    dedicated search-results page (generated by Oxygen).

    THE SIGNAL IS `args.filter`, AND THAT IS THE POINT. The student edition is,
    by definition, the pass filtered through trainee.ditaval - so the scenario
    parameter that MAKES it the student edition is also what identifies it. No
    second parameter to set, and nothing extra to remember when the scenarios
    are rebuilt from scratch.

    A dedicated `webhelp.show.search` parameter was tried first and rejected for
    exactly that reason: an operator who rebuilt the student scenario and forgot
    to re-add it would get a student edition with a dead search box, and nothing
    would say so. Forgetting `args.filter`, by contrast, is impossible to miss -
    the student build comes out carrying the instructor's Analysis Sheets and
    vessel names.

    Oxygen makes this readable because `whr-create-props-file` serialises EVERY
    Ant property of the build (an <echoproperties> with no @prefix), and
    oxyf:getParameter reads that file - so DITA-OT's own parameters are visible
    here alongside the template's.

    The name `trainee.ditaval` is a pipeline constant, not an operator choice:
    generate_dita.py always writes it at the root of its output tree. Matching on the
    filename rather than a substring of the whole path keeps a directory that
    happens to contain "trainee" from flipping the instructor edition.

    Fragment content included via <whc:include_html> is re-processed in
    `copy_template` mode by Oxygen's own commonComponentsExpander.xsl (see
    `includeCustomHTMLContent`), which is what lets this template match inside a
    fragment file rather than a forked page layout.

    WHY NOT INFER FROM PAGE CONTENT. The previous version of this overlay did:
    generate_dita.py stamps an instructor-only <p class="gf-persistent"> marker
    on every TOPIC, the trainee DITAVAL strips it, and the CSS hid the box
    wherever the marker was absent. That inference is only available on pages
    built from a topic. index.html and search.html carry no marker in EITHER
    edition, so the instructor lost the search box on the tiles landing page -
    precisely where a reader arrives and reaches for it.
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:whc="http://www.oxygenxml.com/webhelp/components"
    xmlns:oxyf="http://www.oxygenxml.com/functions"
    exclude-result-prefixes="#all" version="2.0">

    <!-- The DITAVAL that defines the student edition. -->
    <xsl:variable name="trainee-ditaval" as="xs:string" select="'trainee.ditaval'"/>

    <!--
        True when this run is the student edition. args.filter may name several
        DITAVALs separated by the platform path separator, so test each one's
        filename rather than the string as a whole. Compared case-insensitively
        because the target filesystem is: on Windows a scenario pointed at
        TRAINEE.DITAVAL opens the very same file, and must mean the very same
        thing.

        Note the safe direction of failure: anything this does not recognise
        leaves the search box visible. A student edition with a useless search
        box is a wart; an instructor edition without one is a defect.
    -->
    <xsl:variable name="is-student-edition" as="xs:boolean" select="
        some $ditaval in tokenize(translate(lower-case(oxyf:getParameter('args.filter')), '\', '/'), ';')
            satisfies tokenize(normalize-space($ditaval), '/')[last()] = $trainee-ditaval"/>

    <xsl:template match="*:div[contains(@class, 'wh_search_visibility')]" mode="copy_template">
        <xsl:if test="$is-student-edition">
            <!--
                Emit a hidden marker rather than the CSS itself, so the actual
                rule stays in resources/hide-search.css where it can be read and
                overridden like any other style. @hidden keeps the marker out of
                the layout and out of the accessibility tree.
            -->
            <div class="wh_search_visibility wh-search-hidden" hidden="hidden"/>
        </xsl:if>
    </xsl:template>

</xsl:stylesheet>
