<?xml version="1.0" encoding="UTF-8"?>
<!--
    Per-scenario search-box visibility flag (issue #178).

    Fills in the empty placeholder declared by this overlay's
    page-templates-fragments/search-flag.xml, which the publishing template
    binds to the `webhelp.fragment.after.header` extension point - one of the
    few that reaches EVERY generated page type, including the two that are NOT
    built from a topic: the tiles landing page (built from the ditamap) and the
    dedicated search-results page (generated by Oxygen).

    Driven by one custom parameter declared in the template `.opt`:

      webhelp.show.search   yes | no

    Only the exact value "no" hides the box. An unset or misspelled parameter
    therefore leaves the stock behaviour - search visible - which is the safe
    way round: a student edition published with a useless search box is a wart,
    an instructor edition published without one is a defect.

    WHY A BUILD-TIME PARAMETER, NOT A CONTENT MARKER. The previous version of
    this overlay inferred the edition from the page content: generate_dita.py
    stamps an instructor-only <p class="gf-persistent"> marker on every TOPIC,
    the trainee DITAVAL strips it, and the CSS hid the box wherever the marker
    was absent. That inference is only available on pages built from a topic.
    index.html and search.html carry no marker in EITHER edition, so the
    instructor lost the search box on the tiles landing page - precisely where
    a reader arrives and reaches for it.

    The two editions already publish as two transformation scenarios, so the
    edition is known at build time and needs no inferring. The instructor
    scenario takes the template default (yes); the student scenario sets "no".

    Fragment content included via <whc:include_html> is re-processed in
    `copy_template` mode by Oxygen's own commonComponentsExpander.xsl (see
    `includeCustomHTMLContent`), which is what lets this template match inside a
    fragment file rather than a forked page layout.
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:whc="http://www.oxygenxml.com/webhelp/components"
    xmlns:oxyf="http://www.oxygenxml.com/functions"
    exclude-result-prefixes="#all" version="2.0">

    <xsl:template match="*:div[contains(@class, 'wh_search_visibility')]" mode="copy_template">
        <xsl:if test="oxyf:getParameter('webhelp.show.search') = 'no'">
            <!--
                Emit a hidden marker rather than the CSS itself, so the actual
                rule stays in resources/hide-search.css where it can be read and
                overridden like any other style. @hidden keeps the marker out of
                the layout and out of the accessibility tree.
            -->
            <div class="wh_search_visibility wh-search-hidden" hidden="hidden"/>
        </xsl:if>
    </xsl:template>

</xsl:stylesheet>
